### ISSUE TITLE
Change loading screen to say 'crunching'

### ISSUE THREAD

**Issue by jlorich** [cloudspace/angular.crunchinator.com#100]
Seeing as this is the crunchinator and we're crunching data most of the time instead of just loading data, the current loading screen should say 'crunching'.

It would also be nice to see something with a bit of movement while the page is loading so it doesn't appear as if the entire UI thread is locked up.  My thought was a pacman like pie chart eating (crunching) a bar graph.  But anything with movement would look sharp.

**Comment by hkal** [comment]
Updated in #105
